apiConfig:
  configYaml: |-
      name: ${WEBAPP_DEPLOYMENT_NAME}
      webapp:
        domainName: "${API_DNS_NAME}"
        publicUrl: "${WEBAPP_PUBLIC_URL}"
        server:
          nodeSelector:
            "cosmotech.com/tier": "services"
          image:
            pullSecret: ""
            repository: "${IMAGE_REPOSITORY_SERVER}"
            tag: latest
            pullPolicy: Always
        functions:
          nodeSelector:
            "cosmotech.com/tier": "services"
          image:
            pullSecret: ""
            repository: "${IMAGE_REPOSITORY_FUNCTIONS}"
            tag: latest
            pullPolicy: Always
      keycloak:
        realmUrl: "${KEYCLOAK_URL_AUTH}"
      powerbi:
        tenantId: "${POWERBI_APP_TENANT_ID}"
        clientId: "${POWERBI_APP_CLIENT_ID}"
        clientSecret: "${POWERBI_APP_SECRET}"
      ingress:
        enabled: true
      resources:
        limits:
          cpu: 1000m
          memory: 256Mi
        requests:
          cpu: 200m
          memory: 128Mi
host: ${API_DNS_NAME}
hostPathContext: eng-test-dev/brewery-listener
registryUrl: cosmo-tech.github.io/helm-charts/
chartName: cosmotech-business-webapp
chartVersion: ${WEBAPP_CHART_VERSION}
apiGithubWebhookSecret:
  secretToken: ${WEBHOOK_SECRET}
apiDockerSecret:
  dockerconfigjson: ${DOCKER_SECRET}
tolerations:
  - key: "vendor"
    operator: "Equal"
    value: "tekton"
    effect: "NoSchedule"
nodeSelector:
  "cosmotech.com/tier": "services"
  "kubernetes.io/os": "linux"
ingressType: "${INGRESS_TYPE}"
ngrokHost: "${NGROK_HOST}"
useOciRegistry: '"${USE_OCI_REGISTRY}"'
runCypressTests: '"${CP_RUN_TESTS}"'
webAppRepoUrl: "${CP_WEBAPP_URL}"
webAppRevision: "${CP_WEBAPP_REVISION}"
cypressBaseUrl: "https://${API_DNS_NAME}${WEBAPP_PUBLIC_URL}/"
authKeycloakRealm: "${KEYCLOAK_URL_AUTH}"
authKeycloakClientId: "${CP_AUTH_KEYCLOAK_CLIENT_ID}"
authKeycloakClientSecret: "${CP_AUTH_KEYCLOACK_CLIENT_SECRET}"